function(ptgl_add_glfw_example name)
    add_executable(${name} main.cpp)
    target_link_libraries(${name} PRIVATE ptgl)
    if(EMSCRIPTEN)
        target_link_options(${name} PRIVATE -sUSE_GLFW=3)
        set_target_properties(${name} PROPERTIES SUFFIX ".html")
    else()
        find_package(glfw3 CONFIG QUIET)
        if(TARGET glfw)
            set(glfw_target glfw)
        elseif(TARGET glfw3::glfw)
            set(glfw_target glfw3::glfw)
        else()
            if(NOT TARGET ptgl_glfw)
                find_path(GLFW_INCLUDE_DIR GLFW/glfw3.h)
                find_library(GLFW_LIBRARY NAMES glfw3 glfw)
                if(NOT GLFW_INCLUDE_DIR OR NOT GLFW_LIBRARY)
                    message(FATAL_ERROR "Install GLFW or set GLFW_INCLUDE_DIR and GLFW_LIBRARY")
                endif()
                add_library(ptgl_glfw UNKNOWN IMPORTED GLOBAL)
                set_target_properties(ptgl_glfw PROPERTIES
                    IMPORTED_LOCATION "${GLFW_LIBRARY}"
                    INTERFACE_INCLUDE_DIRECTORIES "${GLFW_INCLUDE_DIR}")
            endif()
            set(glfw_target ptgl_glfw)
        endif()
        target_link_libraries(${name} PRIVATE ${glfw_target})
        target_compile_definitions(${name} PRIVATE PTGL_DISABLE_GLES)
        if(MSVC)
            target_compile_options(${name} PRIVATE /utf-8)
        endif()
    endif()
endfunction()
