if(PTGL_BUILD_PLOT_TESTS)
    foreach(test Core Render Figure Xy View)
        add_executable(Plot${test}Tests ${test}Tests.cpp)
        target_link_libraries(Plot${test}Tests PRIVATE ptgl)
        add_test(NAME Plot${test} COMMAND Plot${test}Tests)
    endforeach()
endif()
if(PTGL_BUILD_PLOT_GL_TESTS)
    add_executable(PlotGraphicsTests GraphicsTests.cpp)
    target_link_libraries(PlotGraphicsTests PRIVATE ptgl)
    add_test(NAME PlotGraphics COMMAND PlotGraphicsTests)
endif()
