add_executable(RemoteProtocolTests ProtocolTests.cpp)
target_include_directories(RemoteProtocolTests PRIVATE "${PROJECT_SOURCE_DIR}")
target_compile_features(RemoteProtocolTests PRIVATE cxx_std_17)
add_test(NAME RemoteProtocol COMMAND RemoteProtocolTests)
if(EMSCRIPTEN)
    target_compile_options(RemoteProtocolTests PRIVATE -fexceptions)
    target_link_options(RemoteProtocolTests PRIVATE -fexceptions -sDISABLE_EXCEPTION_CATCHING=0)
else()
    add_executable(RemoteSenderTests SenderTests.cpp SecondTranslationUnit.cpp)
    target_link_libraries(RemoteSenderTests PRIVATE ptgl::remoteSender)
    add_test(NAME RemoteSender COMMAND RemoteSenderTests)
    add_executable(RemoteReceiverTests ReceiverTests.cpp)
    target_link_libraries(RemoteReceiverTests PRIVATE ptgl ptgl::remoteSender)
    add_test(NAME RemoteReceiver COMMAND RemoteReceiverTests)
    set_tests_properties(RemoteSender RemoteReceiver PROPERTIES TIMEOUT 30)
endif()
