# Used both in the source build and by the installed package.
if(NOT TARGET Eigen3::Eigen)
    find_package(Eigen3 CONFIG QUIET)
    if(NOT TARGET Eigen3::Eigen)
        find_path(PTGL_EIGEN_INCLUDE_DIR Eigen/Core
            HINTS "${PTGL_EIGEN_DIR}" "${EIGEN_DIR}"
            PATH_SUFFIXES eigen3 NO_CMAKE_FIND_ROOT_PATH)
        if(NOT PTGL_EIGEN_INCLUDE_DIR)
            message(FATAL_ERROR "Install Eigen3 or set PTGL_EIGEN_DIR to the directory containing Eigen/Core")
        endif()
        add_library(Eigen3::Eigen INTERFACE IMPORTED GLOBAL)
        set_target_properties(Eigen3::Eigen PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${PTGL_EIGEN_INCLUDE_DIR}")
    endif()
endif()
if(NOT EMSCRIPTEN)
    find_package(OpenGL REQUIRED)
    find_package(GLEW REQUIRED)
endif()

if(NOT EMSCRIPTEN)
    find_package(Threads REQUIRED)
    if(TARGET glfw)
        set(PTGL_GLFW_TARGET glfw)
    elseif(TARGET glfw3::glfw)
        set(PTGL_GLFW_TARGET glfw3::glfw)
    else()
        find_package(glfw3 CONFIG QUIET)
        if(TARGET glfw)
            set(PTGL_GLFW_TARGET glfw)
        elseif(TARGET glfw3::glfw)
            set(PTGL_GLFW_TARGET glfw3::glfw)
        else()
            if(NOT TARGET ptgl_glfw)
                find_path(GLFW_INCLUDE_DIR GLFW/glfw3.h)
                find_library(GLFW_LIBRARY NAMES glfw3 glfw)
                if(NOT GLFW_INCLUDE_DIR OR NOT GLFW_LIBRARY)
                    message(FATAL_ERROR "Install GLFW or set GLFW_INCLUDE_DIR and GLFW_LIBRARY")
                endif()
                add_library(ptgl_glfw UNKNOWN IMPORTED GLOBAL)
                set_target_properties(ptgl_glfw PROPERTIES IMPORTED_LOCATION "${GLFW_LIBRARY}"
                    INTERFACE_INCLUDE_DIRECTORIES "${GLFW_INCLUDE_DIR}")
            endif()
            set(PTGL_GLFW_TARGET ptgl_glfw)
        endif()
    endif()
endif()
