add_executable(RemoteViewerDemo Viewer.cpp)
target_link_libraries(RemoteViewerDemo PRIVATE ptgl)
if(EMSCRIPTEN)
    set_target_properties(RemoteViewerDemo PROPERTIES SUFFIX ".html")
    target_link_options(RemoteViewerDemo PRIVATE "--shell-file=${CMAKE_CURRENT_SOURCE_DIR}/WebShell.html")
else()
    add_executable(RemotePublisherDemo Publisher.cpp)
    target_link_libraries(RemotePublisherDemo PRIVATE ptgl::remoteSender)
endif()
if(WIN32 AND NOT EMSCRIPTEN)
    configure_file(RunRemoteDemo.cmd "${CMAKE_BINARY_DIR}/RunRemoteDemo.cmd" COPYONLY)
    configure_file(RunRemoteDemo.ps1 "${CMAKE_BINARY_DIR}/RunRemoteDemo.ps1" COPYONLY)
endif()
